export const AVAILABLE_FONTS = [
    // Sans Serif
    "Inter, sans-serif",
    "Roboto, sans-serif",
    "Open Sans, sans-serif",
    "Lato, sans-serif",
    "Montserrat, sans-serif",
    "Oswald, sans-serif",
    "Raleway, sans-serif",
    "Poppins, sans-serif",
    "Nunito, sans-serif",
    "Ubuntu, sans-serif",
    "Rubik, sans-serif",
    "Work Sans, sans-serif",
    "Quicksand, sans-serif",
    "Karla, sans-serif",
    "Mulish, sans-serif",
    "Cabin, sans-serif",
    "Fira Sans, sans-serif",
    "Josefin Sans, sans-serif",
    "Anton, sans-serif",
    "Bebas Neue, sans-serif",

    // Serif
    "Merriweather, serif",
    "Playfair Display, serif",
    "Lora, serif",
    "PT Serif, serif",
    "Noto Serif, serif",
    "Libre Baskerville, serif",
    "Crimson Text, serif",
    "Bitter, serif",
    "Arvo, serif",
    "EB Garamond, serif",
    "Domine, serif",
    "Georgia, serif",
    "Times New Roman, serif",

    // Monospace
    "Roboto Mono, monospace",
    "Fira Code, monospace",
    "Source Code Pro, monospace",
    "Inconsolata, monospace",
    "Ubuntu Mono, monospace",
    "Courier New, monospace",
    "Space Mono, monospace",
    "JetBrains Mono, monospace",
    "IBM Plex Mono, monospace",
    "Nanum Gothic Coding, monospace",

    // Display / Handwriting / Cursive
    "Pacifico, cursive",
    "Dancing Script, cursive",
    "Shadows Into Light, cursive",
    "Lobster, cursive",
    "Comfortaa, cursive",
    "Caveat, cursive",
    "Satisfy, cursive",
    "Great Vibes, cursive",
    "Comic Sans MS, cursive",
    "Abril Fatface, cursive",
    "Righteous, cursive",
    "Fredoka One, cursive",
    "Permanent Marker, cursive",
    "Patua One, cursive",
    "Creepster, cursive",
];
